### ISSUE TITLE
Cannot find some imports

### ISSUE THREAD

**Issue by Zlatokosa** [j-cb/GOOD#26]
I want to do experiments on exactly the same datasets as you did. 
However, I can't seem to find some imports in code:
```
paths_config
tiny_utils.tinyimages_80mn_loader
noisefunctions

```
Also, I am wondering did you perhaps stored the datasets you used somewhere where is available to reach it? E.g. if I use LSUN_classrom, I will be missing to use exactly same images as you did in your experiments from the larger dataset.

Thank you for your help.

**Comment by j-cb** [comment]
The imports should usually work when the script is run from the repo's main folder, which includes `paths_config.py`, `noisefunctions.py` and `tiny_utils/tinyimages_80mn_loader.py`.

Could you describe what code you run when then imports fail?

**Comment by j-cb** [comment]
The LSUN_classroom evaluation uses the standard dataset from the torchvision library which can be set up as described here:  http://pytorch.org/vision/main/generated/torchvision.datasets.LSUN.html

To obtain the classroom subset, `dataloading.py` loads the dataset as follows:

```
classes = ['classroom_val']
dset = datasets.LSUN(paths_config.location_dict['LSUN'], classes=classes, transform=transform)
```
